// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFFmpegVersion():Promise<string>;

export function GetVideoDuration(arg1:string):Promise<number>;

export function IsEnvironmentReady():Promise<boolean>;

export function SelectDirectory():Promise<string>;

export function SelectFile():Promise<string>;

export function SplitVideo(arg1:string,arg2:number,arg3:number,arg4:string,arg5:string,arg6:string):Promise<void>;
