// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFFmpegVersion() {
  return window['go']['main']['App']['GetFFmpegVersion']();
}

export function GetVideoDuration(arg1) {
  return window['go']['main']['App']['GetVideoDuration'](arg1);
}

export function IsEnvironmentReady() {
  return window['go']['main']['App']['IsEnvironmentReady']();
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SplitVideo(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SplitVideo'](arg1, arg2, arg3, arg4, arg5, arg6);
}
